---
# MD013/line-length - Line length
MD013:
  tables: false

# MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
MD024:
  siblings_only: true

# MD042/no-empty-links - No empty links
MD042: false
