name: autotest

# https://docs.github.com/en/actions/reference
# https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
# https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts
# https://github.github.io/actions-cheat-sheet/actions-cheat-sheet.pdf
#
# TODO:
# - Create a test result branch: `REPO/test-results`.
# - Commit test outputs to the test result branch.
# https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action/58393457#58393457


concurrency:
  group: autotest
  cancel-in-progress: true

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened ]
    paths-ignore:
      - 'LICENSE'
      - '**.md'
      - '**.rst'
  push:
    branches:
      - master
      - quantimnot-gh-actions
    paths-ignore:
      - 'LICENSE'
      - '**.md'
      - '**.rst'

jobs:
  noskipci:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "not contains '[skip ci]'"
  autotest:
    runs-on: ${{ matrix.buildHost }}
    needs: noskipci
    strategy:
      fail-fast: false
      matrix:
        buildHost:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        platform:
          # - linux
          # - macosx
          # - windows
          # - js
          - emscripten
          # - wasm
          # - ios
          # - ios-sim
          # - android
          # - android-sim
        browser:
          # - chrome
          - firefox
          # - safari
          # - android-chrome
          # - ios-safari
          - none
        nim-version:
          - devel
        exclude:
          - platform: linux
            browser: chrome
          - platform: linux
            browser: firefox
          - platform: linux
            browser: safari
          - platform: linux
            browser: android-chrome
          - platform: linux
            browser: ios-safari

          - platform: js
            browser: none
          - platform: emscripten
            browser: none
          - platform: wasm
            browser: none

          - platform: macosx
            browser: chrome
          - platform: macosx
            browser: firefox
          - platform: macosx
            browser: android-chrome

          - platform: windows
            browser: chrome
          - platform: windows
            browser: firefox
          - platform: windows
            browser: safari
          - platform: windows
            browser: android-chrome
          - platform: windows
            browser: ios-safari

          - platform: ios
            browser: chrome
          - platform: ios
            browser: firefox
          - platform: ios
            browser: safari
          - platform: ios
            browser: android-chrome
          - platform: ios
            browser: ios-safari

          - platform: ios-sim
            browser: chrome
          - platform: ios-sim
            browser: firefox
          - platform: ios-sim
            browser: safari
          - platform: ios-sim
            browser: android-chrome
          - platform: ios-sim
            browser: ios-safari

          - platform: android
            browser: chrome
          - platform: android
            browser: firefox
          - platform: android
            browser: safari
          - platform: android
            browser: android-chrome
          - platform: android
            browser: ios-safari

          - platform: android-sim
            browser: chrome
          - platform: android-sim
            browser: firefox
          - platform: android-sim
            browser: safari
          - platform: android-sim
            browser: android-chrome
          - platform: android-sim
            browser: ios-safari

          - buildHost: ubuntu-latest
            platform: macosx
          - buildHost: ubuntu-latest
            platform: windows
          - buildHost: ubuntu-latest
            platform: ios
          - buildHost: ubuntu-latest
            platform: ios-sim
          - buildHost: ubuntu-latest
            browser: safari
          - buildHost: ubuntu-latest
            browser: ios-safari

          - buildHost: macos-latest
            platform: linux
          - buildHost: macos-latest
            platform: windows
          - buildHost: macos-latest
            platform: android
          - buildHost: macos-latest
            platform: android-sim
          - buildHost: macos-latest
            browser: chrome
          - buildHost: macos-latest
            browser: firefox
          - buildHost: macos-latest
            browser: android-chrome

          - buildHost: windows-latest
            platform: linux
          - buildHost: windows-latest
            platform: macosx
          - buildHost: windows-latest
            platform: ios
          - buildHost: windows-latest
            platform: ios-sim
          - buildHost: windows-latest
            platform: android
          - buildHost: windows-latest
            platform: android-sim
          - buildHost: windows-latest
            platform: js
          - buildHost: windows-latest
            platform: emscripten
          - buildHost: windows-latest
            platform: wasm
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ matrix.buildHost }}-nimble-${{ hashFiles('*.nimble') }}
      - id: cache-choosenim
        uses: actions/cache@v1
        with:
          path: ~/.choosenim
          key: ${{ matrix.buildHost }}-choosenim }}
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
      - run: nim r .github/workflows/build ${{ matrix.platform }} ${{ matrix.browser }}
