name: build

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# https://docs.github.com/en/actions/reference
# https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
# https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts
# https://github.github.io/actions-cheat-sheet/actions-cheat-sheet.pdf
# https://github.com/actions/checkout
# https://github.com/actions/cache
#
# TODO:
# - Create a test result branch: `REPO/test-results`.
# - Commit test outputs to the test result branch.
# https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action/58393457#58393457


concurrency:
  group: build
  cancel-in-progress: true

on:
  push:
    branches:
      - test-github-actions

jobs:
  noskipci:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "not contains '[skip ci]'"
  build:
    runs-on: ${{ matrix.buildHost }}
    needs: noskipci
    strategy:
      fail-fast: false
      matrix:
        buildHost:
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        platform:
          - linux-native
          # - android-native
          # - android-sim
          # - firefox-js
          # - chrome-js
          # - android-chrome-js
          # - firefox-emscripten
          # - chrome-emscripten
          # - android-chrome-emscripten
          # - firefox-wasm
          # - chrome-wasm
          # - android-chrome-wasm
          # - macos-native
          # - ios-native
          # - ios-sim
          # - safari-js
          # - ios-safari-js
          # - safari-emscripten
          # - ios-safari-emscripten
          # - safari-wasm
          # - ios-safari-wasm
          # - windows-native
          # - edge-js
          # - edge-emscripten
          # - edge-wasm
        nim:
          - stable
          # - devel
    steps:
      - uses: actions/checkout@v2
      - id: cache-nimble
        uses: actions/cache@v2
        with:
          path: ~/.nimble
          key: ${{ matrix.buildHost }}-nimble-${{ hashFiles('*.nimble') }}
      - id: cache-choosenim
        uses: actions/cache@v2
        with:
          path: ~/.choosenim
          key: ${{ matrix.buildHost }}-choosenim }}
      - id: install-nim
        run: |
          curl -LsSf https://nim-lang.org/choosenim/init.sh > choosenim.sh
          sh choosenim.sh -y
          export PATH=/home/runner/.nimble/bin:$PATH
          echo "PATH=/home/runner/.nimble/bin:$PATH" >> $GITHUB_ENV
          choosenim ${{ matrix.nim }}
      - id: build
        continue-on-error: true # continue so that the `diag` step can be triggered
        run: nim r ${{ matrix.platform }}/build
      - id: debug
        if: contains(github.event.head_commit.message, '[debug ci]')
        run: |
          echo debug_keys=debug_keys_${{ github.actor }} >> $GITHUB_ENV
          echo ${{ secrets[env.debug_keys] }} | ./${{ matrix.buildHost }}-debug.sh
